version: "3.9"

services:
  nextjs-app:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/demosratio
      - NODE_ENV=development
    volumes:
      - ./client:/app
      - ./client/.next:/app/.next
    restart: unless-stopped
    networks:
      - app-network

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    volumes:
      - ./auth:/app
    restart: unless-stopped
    networks:
      - app-network

  proposals:
    build:
      context: ./proposals
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./proposals:/app
    restart: unless-stopped
    networks:
      - app-network

  parliament-data-extractor:
    build:
      context: ./parliamentDataExtractor
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DAYS_TO_CHECK_VOTATIONS=10
    volumes:
      - ./parliamentDataExtractor:/app
    restart: unless-stopped
    networks:
      - app-network

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demosratio
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
