version: "3.9"

services:
  nextjs-app-prod:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/demosratio
      - NODE_ENV=production
    restart: unless-stopped

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - JWT_KEY=demosratio_Key
      - NODE_ENV=production
      - CLIENT_URL=http://localhost:3000 # Change it for prod
    depends_on:
      - postgres
    volumes:
      - ./auth:/app
    restart: unless-stopped

  proposals:
    build:
      context: ./proposals
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - CLIENT_URL=http://localhost:3000 # Change it for prod
      - JWT_KEY=demosratio_Key
    depends_on:
      - postgres
    volumes:
      - ./proposals:/app
    restart: unless-stopped

  parliament-data-extractor:
    build:
      context: ./parliamentDataExtractor
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DAYS_TO_CHECK_VOTATIONS=400
    volumes:
      - ./parliamentDataExtractor:/app
    restart: unless-stopped

  postgres:
    image: postgres:15
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demosratio
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data across container restarts

volumes:
  postgres_data:

networks:
  app-network:
