-- Proposal summaries generated by AI
-- Stores citizen-friendly bullet-point summaries of congressional proposals
-- summary_type: 'title-based' (from title/expedient only) or 'enriched' (from scraped content, future)
CREATE TABLE IF NOT EXISTS proposal_summaries (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 proposal_id BIGINT NOT NULL REFERENCES proposals(id) ON DELETE CASCADE,
 summary_text TEXT NOT NULL,
 summary_type VARCHAR(20) NOT NULL DEFAULT 'title-based',
 created_at TIMESTAMPTZ DEFAULT NOW(),
 updated_at TIMESTAMPTZ DEFAULT NOW(),
 UNIQUE(proposal_id)
);

-- Index for quick lookup by proposal_id
CREATE INDEX IF NOT EXISTS idx_proposal_summaries_proposal_id ON proposal_summaries(proposal_id);

-- Auto-update updated_at on row change
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
 NEW.updated_at = NOW();
 RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_proposal_summaries_updated_at ON proposal_summaries;
CREATE TRIGGER update_proposal_summaries_updated_at
 BEFORE UPDATE ON proposal_summaries
 FOR EACH ROW
 EXECUTE FUNCTION update_updated_at_column();
